apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-redis-config
  namespace: redis
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru 
    bind 0.0.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: REDIS_PASSWORD
      value: "test1234"
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: test-redis-config
        items:
        - key: redis-config
          path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: redis
spec:
  clusterIP: 10.96.84.2
  selector:
    app: redis
  ports:
    - name: ingest
      protocol: TCP
      port: 6379
      targetPort: 6379