---
# Default values for logstream-leader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

criblImage:
  repository: cribl/cribl
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 4.1.2

imagePullSecrets: []
nameOverride: "leader"
fullnameOverride: ""
iter: 1

autoscaling:
  enabled: false

config:
  scName:
  license:
  token: myworkergrouptokenforsecurity
  adminPassword: myowncribl
  criblHome: /opt/cribl
  bindHost: 0.0.0.0
  rejectSelfSignedCerts: 0
  # -- Perform health checks on the Leader pod.
  # Recommended that this be enabled to automatically restart the Leader if the Pod is unhealthy
  probes: true
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 9000
      scheme: HTTP
    initialDelaySeconds: 60
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/v1/health
      port: 9000
      scheme: HTTP
    initialDelaySeconds: 60
    failureThreshold: 3
  groups: ["group1"]

env: {}

#added Persistent Volume Configuration
extraVolumeMounts:
- name: cribl
  mountPath: /opt/cribl/config-volume/
  subPath: cribl
  existingClaim: pvc-root-host-volume-cribl
  readOnly: false
  
service:
  internalType: ClusterIP
  externalType: LoadBalancer
  annotations: {}
  ports:
    - name: api
      port: 9000
      protocol: TCP
      external: true
    - name: leadercomm
      port: 4200
      protocol: TCP
      external: false

strategy:
  type: Recreate
  rollingUpdate:
    maxSurge:
    maxUnavailable:

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enable: false
  annotations: {}
  tls: {}
#    - hosts:
#        - cribl.example.com
#      secretName: cribl-example-com-tls
  prefix: /*
  ingressClassName:
  host:

resources:
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 500m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}